defaults: &defaults
  fog_provider: "AWS"
  fog_directory: "apollo-music"
  aws_access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  aws_secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  existing_remote_files: delete

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
