development:
  adapter: postgresql
  encoding: unicode
  database: apollo-dev
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: apollo-test
  pool: 5
  username: postgres
  password:


