common: &default_settings

  license_key: ENV['NEWRELIC_KEY']

  app_name: ENV['APP_NAME']

  monitor_mode: true

  developer_mode: false

  log_level: info

  browser_monitoring:
      # By default the agent automatically injects the monitoring JavaScript
      # into web pages. Set this attribute to false to turn off this behavior.
      auto_instrument: true

  audit_log:
    enabled: false

  capture_params: false

  transaction_tracer:

    enabled: true

    transaction_threshold: apdex_f

    record_sql: obfuscated

    stack_trace_threshold: 0.500

  error_collector:

    enabled: true

    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"

